[project]
name = "generative-ai-in-action"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.5",
    "openai>=2.11.0",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
    "tiktoken>=0.12.0",
]
